CREATE TABLE MANAGER (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  cognito_id VARCHAR2(255) NOT NULL UNIQUE,
  name VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) NOT NULL,
  phone_number VARCHAR2(50) NOT NULL
);

CREATE TABLE TENANT (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  cognito_id VARCHAR2(255) NOT NULL UNIQUE,
  name VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) NOT NULL,
  phone_number VARCHAR2(50) NOT NULL
);

CREATE TABLE LOCATION (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  address VARCHAR2(255) NOT NULL,
  city VARCHAR2(100) NOT NULL,
  state VARCHAR2(100) NOT NULL,
  country VARCHAR2(100) NOT NULL,
  postal_code VARCHAR2(20) NOT NULL,
  latitude NUMBER(10, 6) NOT NULL,
  longitude NUMBER(10, 6) NOT NULL
);

CREATE TABLE PROPERTY (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  description CLOB NOT NULL,
  price_per_month NUMBER(10, 2) NOT NULL,
  security_deposit NUMBER(10, 2) NOT NULL,
  application_fee NUMBER(10, 2) NOT NULL,
  photo_urls CLOB CHECK (photo_urls IS JSON),
  amenities CLOB CHECK (amenities IS JSON),
  highlights CLOB CHECK (highlights IS JSON),
  is_pets_allowed NUMBER(1) DEFAULT 0 NOT NULL,
  is_parking_included NUMBER(1) DEFAULT 0 NOT NULL,
  beds NUMBER(3) NOT NULL,
  baths NUMBER(4, 1) NOT NULL,
  square_feet NUMBER(6) NOT NULL,
  property_type VARCHAR2(50) NOT NULL,
  posted_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  average_rating NUMBER(3, 2) DEFAULT 0,
  number_of_reviews NUMBER(6) DEFAULT 0,
  location_id NUMBER NOT NULL,
  manager_cognito_id VARCHAR2(255) NOT NULL,
  CONSTRAINT property_location_fk FOREIGN KEY (location_id) REFERENCES LOCATION (id),
  CONSTRAINT property_manager_fk FOREIGN KEY (manager_cognito_id) REFERENCES MANAGER (cognito_id),
  CONSTRAINT property_pets_chk CHECK (is_pets_allowed IN (0, 1)),
  CONSTRAINT property_parking_chk CHECK (is_parking_included IN (0, 1))
);

CREATE TABLE LEASE (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  rent NUMBER(10, 2) NOT NULL,
  deposit NUMBER(10, 2) NOT NULL,
  property_id NUMBER NOT NULL,
  tenant_cognito_id VARCHAR2(255) NOT NULL,
  CONSTRAINT lease_property_fk FOREIGN KEY (property_id) REFERENCES PROPERTY (id),
  CONSTRAINT lease_tenant_fk FOREIGN KEY (tenant_cognito_id) REFERENCES TENANT (cognito_id)
);

CREATE TABLE APPLICATION (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  application_date TIMESTAMP NOT NULL,
  status VARCHAR2(20) NOT NULL,
  property_id NUMBER NOT NULL,
  tenant_cognito_id VARCHAR2(255) NOT NULL,
  name VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) NOT NULL,
  phone_number VARCHAR2(50) NOT NULL,
  message CLOB,
  lease_id NUMBER UNIQUE,
  CONSTRAINT application_property_fk FOREIGN KEY (property_id) REFERENCES PROPERTY (id),
  CONSTRAINT application_tenant_fk FOREIGN KEY (tenant_cognito_id) REFERENCES TENANT (cognito_id),
  CONSTRAINT application_lease_fk FOREIGN KEY (lease_id) REFERENCES LEASE (id)
);

CREATE TABLE PAYMENT (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  amount_due NUMBER(10, 2) NOT NULL,
  amount_paid NUMBER(10, 2) NOT NULL,
  due_date TIMESTAMP NOT NULL,
  payment_date TIMESTAMP NOT NULL,
  payment_status VARCHAR2(20) NOT NULL,
  lease_id NUMBER NOT NULL,
  CONSTRAINT payment_lease_fk FOREIGN KEY (lease_id) REFERENCES LEASE (id)
);

CREATE TABLE TENANT_FAVORITES (
  tenant_cognito_id VARCHAR2(255) NOT NULL,
  property_id NUMBER NOT NULL,
  CONSTRAINT tenant_favorites_pk PRIMARY KEY (tenant_cognito_id, property_id),
  CONSTRAINT tenant_favorites_tenant_fk FOREIGN KEY (tenant_cognito_id) REFERENCES TENANT (cognito_id),
  CONSTRAINT tenant_favorites_property_fk FOREIGN KEY (property_id) REFERENCES PROPERTY (id)
);

CREATE TABLE TENANT_PROPERTIES (
  tenant_cognito_id VARCHAR2(255) NOT NULL,
  property_id NUMBER NOT NULL,
  CONSTRAINT tenant_properties_pk PRIMARY KEY (tenant_cognito_id, property_id),
  CONSTRAINT tenant_properties_tenant_fk FOREIGN KEY (tenant_cognito_id) REFERENCES TENANT (cognito_id),
  CONSTRAINT tenant_properties_property_fk FOREIGN KEY (property_id) REFERENCES PROPERTY (id)
);

CREATE INDEX property_manager_idx ON PROPERTY (manager_cognito_id);
CREATE INDEX property_location_idx ON PROPERTY (location_id);
CREATE INDEX lease_property_idx ON LEASE (property_id);
CREATE INDEX lease_tenant_idx ON LEASE (tenant_cognito_id);
CREATE INDEX application_property_idx ON APPLICATION (property_id);
CREATE INDEX application_tenant_idx ON APPLICATION (tenant_cognito_id);
CREATE INDEX payment_lease_idx ON PAYMENT (lease_id);
